name: code-verify
on:
  push:
    branches:
      - "feature/*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Validate sonar analysis result
        shell: bash
        env:
          PROJECT_KEY: Isla-del-Lago_isla-del-lago-web-ui
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "Analysis on branch ${GITHUB_REF#refs/heads/}"
          projectStatus=$(curl --location --request GET "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECT_KEY&branch=${GITHUB_REF#refs/heads/}" --header "Authorization: Bearer $SONAR_TOKEN")

          projectStatusErrorString=*"\"projectStatus\":{\"status\":\"ERROR\""*

          echo "$projectStatus"

          if [[ $projectStatus ==  $projectStatusErrorString ]];
          then
              echo "Project status error found"
              exit 1
          else
              echo "Project status error not found"
          fi
